### ISSUE TITLE
input placeholder problem

### ISSUE THREAD

**Issue by shadihrr** [Sadeghbayan/Angular-Directive-Persian-DatePickerJqueryUi#1]
if you add a placeholder to the datepicker input tag the placeholder appears with no padding from the begining of the input. how can I change this.
 Thank you in advance

**Comment by Sadeghbayan** [comment]
The input is not able to have a placeholder because of ui mask directive .

**Comment by shadihrr** [comment]
Thank you for your reply. So how can I change the ui mask directive properties in order to change the text's position (add padding or margin).

**Comment by Sadeghbayan** [comment]
check this : http://plnkr.co/edit/pJ3ulKK9wBPwnADpVFkb?p=preview  

added padding-left to input in css
