### ISSUE TITLE
How to install??

### ISSUE THREAD

**Issue by mehrdad-shokri** [Sadeghbayan/Angular-Directive-Persian-DatePickerJqueryUi#2]
Hey, any npm package? or pre-built scripts?  
What should be included?

**Comment by Sadeghbayan** [comment]
Hi Mehrdad , there is no npm package for this directive at the moment, but you can take look at this plunk : http://plnkr.co/edit/2nhFx3yPGnlCrDn8eyna?p=preview.

BTW you should include these files : bootstrap-datepicker.js , bootstrap-datepicker.fa.js
